### ISSUE TITLE
non-interactive mode for fly

### ISSUE THREAD

**Issue by prein** [JulzDiverse/aviator#25]
I would like to use aviator in a meta (concourse) pipeline creating other pipelines. For that to be possible fly needs to be run in non-interactive mode (with -n argument).

I would appreciate adding an option along the lines of:
```
fly:
  non-interactive: true
```
that would result appending '-n' to fly args

**Comment by JulzDiverse** [comment]
Hi @prein,

The `non-interactive` mode was added to the fly-executor. You can check the details in the latest release-notes or in the README. 

Please note that I introduced a breaking change:
- the fly `vars` property was renamed to `load_vars_from` (matching the fly `--load-vars-from` param)
- `vars` is now a new feature, which supports the fly `--var` flag.

**Comment by prein** [comment]
Many thanks @JulzDiverse ! Works as expected.
