### ISSUE TITLE
Passing error code from fly

### ISSUE THREAD

**Issue by prein** [JulzDiverse/aviator#28]
Hi, 
Not sure if my finding is correct but it looks to me that if fly errors out, then (not every?) exit code from fly gets passed down as aviator exit code.
Since my use case is CI, I care for the pipeline to fail in case of error.

The behavior I am observing:
Add a "put" to pipeline definition with misspelled name, or in any other way not existing among the pipeline resources, say:
```
   - put: docker-imag
      params:
        build: build-result
```
Run set-pipeline with fly directly:
`fly  -t target sp -p pipeline-foo -c pipeline-foo.yml -n`
Result:

```
[...]
apply configuration? [yN]: y
error: invalid configuration:
invalid jobs:
	jobs.pipeline-foo.plan[5].put.docker-imag refers to a resource that does not exist

$ echo $?
1
```

Doing the same with aviator. My aviator-foo.yml for testing:
```
fly:
  target: target
  name: pipeline-foo
  config: pipeline-foo.yml
  non_interactive: true
```
Running:
`aviator -f aviator-foo.yml`
Result:
```
[...]
apply configuration? [yN]: y
error: invalid configuration:
invalid jobs:
	jobs.pipeline-foo.plan[5].put.docker-imag refers to a resource that does not exist

$ echo $?
0
```
For errors from fly, like this one, it would help me if aviator exited with non-zero code. Is it possible to do? Thanks in advance.

**Comment by JulzDiverse** [comment]
Hi @prein, 
thx for opening this issue and for the finding. Fly errors are now handled by `aviator`. The new release:   https://github.com/JulzDiverse/aviator/releases/tag/v0.19.0 should fix the issue.

**Comment by JulzDiverse** [comment]
Hi @prein
can this issue be closed?

**Comment by JulzDiverse** [comment]
closing this issue. Feel free to re-open it in case it did not solve the problem.

**Comment by prein** [comment]
Thanks @JulzDiverse and apologies for delays. It is working as expected.
