### ISSUE TITLE
[feature] fly executor performing "validate-pipeline"

### ISSUE THREAD

**Issue by aegershman** [JulzDiverse/aviator#32]
https://github.com/JulzDiverse/aviator#the-fly-section-optional

Similar to how the `kubectl` executor has a `--dry-run` mode, perhaps it would be beneficial to have the `fly` executor only do a `validate-pipeline` and not _actually_ fly up the pipeline.

Thanks for your time and consideration.

**Comment by JulzDiverse** [comment]
Hi @aegershman
thx for open this issue. I think that is very good idea, i'll add it to the fly-executor. It will be part of the next release.

**Comment by JulzDiverse** [comment]
Hi @aegershman 
check out the new release: https://github.com/JulzDiverse/aviator/releases/tag/v1.4.0
It has the requested update ;)
