### ISSUE TITLE
Exposed pipelines can't be hidden

### ISSUE THREAD

**Issue by mattburgess** [JulzDiverse/aviator#35]
Currently, if you set `expose: true` your pipeline will be hidden. Setting it to false, though, does nothing. I've opened a PR at #34 which enables previously exposed pipelines to be hidden again.

**Comment by JulzDiverse** [comment]
Hey @mattburgess,
good point. Thanks for the PR. I already merged it and i will create a new release soon.

**Comment by JulzDiverse** [comment]
Hey @mattburgess,
the new release is now available and includes your fix: https://github.com/JulzDiverse/aviator/releases/tag/v1.5.0 
Thx again!
