### ISSUE TITLE
Render to STDOUT

### ISSUE THREAD

**Issue by 1fox1** [JulzDiverse/aviator#36]
Sometimes it would useful to be able to render to stdout instead of having to create a file.

**Comment by JulzDiverse** [comment]
Hey @1fox1,
thank you for opening this issue. 
I think it makes perfectly sense to have such a feature. Could be really useful when creating new `aviator.yml` files and to validate the results. 
I added a `--dry-run` flag to aviator. It is global and will print any file that used to be written to a file to stdout instead. At the same time it omits any defined executor. 
I will release a new version very soon (which will include this feature).

**Comment by JulzDiverse** [comment]
Hi @1fox1,
the new release is now available: https://github.com/JulzDiverse/aviator/releases/tag/v1.5.0

**Comment by 1fox1** [comment]
Thanks very much Julz.

**Comment by 1fox1** [comment]
I wanted to use the output in a pipe to a second command.
As the merge info as below is also rendered to stdout it is not possible.
I think it would cut down on the possible need for certain executors, for example I wanted to try this out https://get-kapp.io/ (its the deployment tool from ytt guys)

Sorry for not being clear in my request. --dry-run I didn't think of and is very useful.

`SPRUCE MERGE:
	b.yml
	a.yml
	to: afile


RESULT:`
