### ISSUE TITLE
fly set-pipeline bails out unless non_interactive = True

### ISSUE THREAD

**Issue by mattburgess** [JulzDiverse/aviator#37]
I've just upgraded to 1.5.0 and am seeing the following behaviour:

Running `aviator`, it gets to this part:

`AVIATOR EXECUTE:$ fly --target concourse set-pipeline --pipeline mypipeline --config aviator_pipeline.yml`

and prints out the correct diff, but then immediately prints `bailing out` rather than prompting me to accept the change.  I can work around this by setting `non_interactive: true` in `aviator.yml`.  I couldn't see anything related in the recent releases that suggests I've missed some other bit of config, but am quite happy to pointed at it if there was a breaking change along the way.  Thanks!

**Comment by JulzDiverse** [comment]
Hi @mattburgess,

That was probably an accident when I implemented the `dry-run` feature. I fixed it and created a new release `v1.6.0`. Sorry for that and thank you very much for opening the issue and reporting the bug.

**Comment by mattburgess** [comment]
@JulzDiverse that's a very impressive turnaround! Just tested the new release and works as expected. Thanks a lot for fixing that so quickly!
